#!/bin/bash
# run slim in parallel (locally or on a Hadoop cluster)
# Rupert Mazzucco, 2021-2023

version="0.0.9010"

usage="
  Usage: $0 -i <script.slim> {-n <nsims> | -p <params.txt>} [...]

  Run SLiM in parallel locally or on a Hadoop cluster. In its simplest form,
  parallel instances of the provided script are run locally with different
  random number seeds, and their output is captured and placed in numbered
  files in the local folder. In its most complex form, seeds and other script
  parameters are provided in a file, slim instances are run on the cluster,
  and specified output files are collected in a designated output folder.
  
  For running locally, slim and GNU parallel need to be found in the PATH. For
  running on a Hadoop cluster, a TAR archive containing slim must be provided via the
  --execarch argument. If hadoop is not found, use --hadoop-prefix. If the hadoop
  command does not find the cluster, use --hadoop-conf-dir to point to the correct
  configuration.

  Version: $version

  Mandatory arguments:

  -i | --in              ... a SLiM script describing the simulation, possibly
                             using Eidos constants to be set on the command line
  -n | --nreps           ... number of replicate simulations to run (ignored if -p is provided)

  Optional arguments:

  -p | --parameters      ... text file providing simulation parameters in tab-
                             separated columns with a header line for a number
                             of simulations equal to the number of non-header lines;
                             column names and values are provided to slim using
                             slim's '-define <name>=<value>' command line option with
                             exception of the special column 'seed', which, if
                             provided, is passed using the '-seed <value>' option
                             to set an initial seed for SLiM's random number generator;
                             and the column 'files', which contains a comma-separated
                             list of task-specific files to be copied or downloaded to the
                             1files/ subfolder of the execution folder. Parameters and
                             parameter names cannot contain white space.
  -s | --seed            ... master seed from which seeds for all simulations are
                             generated by adding an offset from 0 to <nsims>-1
                             ignored if seeds are provided in the parameter file
                             (default: 4711)
  -f | --files           ... comma-separated list of files that swill be provided
                             to slim in the 0files/ subfolder of the local folder;
                             unlike files listed in the parameter file, these will
                             be identical for all simulation tasks
  -o | --out             ... folder where simulation outputs are collected
  -t | --threads         ... number of threads to use, ignored when running on
                             a Hadoop cluster (default: half the available cores)
  -N | --niceness        ... niceness to run at locally (default: 5)

  -r | --remote                   ... run on a Hadoop cluster instead of locally
  -H | --hadoop-prefix <folder>   ... where to find the hadoop command (default: PATH)
  -C | --hadoop-conf-dir <folder> ... Hadoop configuration (default: HADOOP_CONF_DIR if set,
                                                            or the hadoop command default)
  -J | --java-home <folder>       ... where to find java (default: JAVA_HOME if set, or PATH)
  -X | --execarch <archive>       ... path to a tar.gz archive containing on the top level
                                      a slim executable that can run on the cluster
  -K | --kill-after-msecs <integer>  ... a timeout for cluster tasks in milliseconds (default: no timeout)
  -M | --memory-for-tasks-mb         ... memory limit for cluster tasks in MB (default: 4096)

  -T | --tmpdir <folder>  ... folder for temporary files (default: TMPDIR if set, or /tmp)
  -k | --keep             ... do not delete the working folder upon exit
  -D | --dry-run          ... do not run the actual simulation tasks

  -h | --help             ... display this help text
  -v | --version          ... display version information
"
# more configuration through environment variables
PSLIM_SLIM_PATH=${PSLIM_SLIM_PATH:-"/usr/bin/slim"}
PSLIM_HDFS_WPATH=${PSLIM_HDFS_WPATH:-"/user/$USER/pslim"}
PSLIM_HDFS_TPATH=${PSLIM_HDFS_TPATH:-"/tmp/pslim/$USER"}

# helpers
function pinfo
{
  printf 'INFO:\t%s\n' "$1"
} >&2
function pwarn
{
  printf 'WARN:\t%s\n' "$1"
} >&2
function perror
{
  printf 'ERROR:\t%s\n' "$1"
} >&2

# save command line before we do anything else with it
cmdline="$*"

### Parse command line

# translate long options to short
# a refinement of https://stackoverflow.com/a/5255468/519360
reset="true"
for arg in "${@//=/ }"; do
  if [[ -n "$reset" ]]; then
    unset reset
    set --      # this resets the "$@" array so we can rebuild it
  fi
  case "$arg" in
    --in)                   set -- "$@" -i ;;
    --nreps)                set -- "$@" -n ;;
    --parameters)           set -- "$@" -p ;;
    --seed)                 set -- "$@" -s ;;
    --files)                set -- "$@" -f ;;
    --out)                  set -- "$@" -o ;;
    --threads)              set -- "$@" -t ;;
    --niceness)             set -- "$@" -N ;;
    --remote)               set -- "$@" -r ;;
    --hadoop-prefix)        set -- "$@" -H ;;
    --hadoop-conf-dir)      set -- "$@" -C ;;
    --java-home)            set -- "$@" -J ;;
    --execarch)             set -- "$@" -X ;;
    --kill-after-msecs)     set -- "$@" -K ;;
    --memory-for-tasks-mb)  set -- "$@" -M ;;
    --tmpdir)               set -- "$@" -T ;;
    --keep)                 set -- "$@" -k ;;
    --dry-run)              set -- "$@" -D ;;
    --version)              set -- "$@" -v ;;
    --help)                 set -- "$@" -h ;;
    --usage)                set -- "$@" -h ;;
    # pass through anything else
    *)                  set -- "$@" "$arg" ;;
  esac
done
# now we can process with getopt
# defaults where we need them
ARG_SEED=4711
ARG_NICENESS=5
# TODO reset to "false" after testing remote branch!
ARG_REMOTE="false"
ARG_DRYRUN="false"
ARG_TIMEOUT=0
ARG_MEM=4096
ARG_KEEP="false"
ARG_NREPS=1
ARG_THREADS=${ARG_THREADS:-$(($(getconf _NPROCESSORS_ONLN)/2))}
while getopts ":i:n:p:s:f:o:O:t:N:rH:C:J:X:K:M:TDkhv" opt; do
  case $opt in
    i) ARG_SLIMSCRIPT="$(realpath "$OPTARG")" ;;
    n) ARG_NREPS="$OPTARG" ;;
    p) ARG_PARAMS="$(realpath "$OPTARG")" ;;
    s) ARG_SEED="$OPTARG" ;;
    # TODO make this a proper array to avoid problems with blanks in file names
    f) ARG_FILES="$(echo "$OPTARG" | tr ',' ' ')";;
    o) ARG_OPATH="$(realpath "$OPTARG")" ;;
    t) ARG_THREADS="$OPTARG" ;;
    N) ARG_NICENESS="$OPTARG" ;;
    r) ARG_REMOTE="true" ;;
    H) HADOOP_PREFIX="$OPTARG"; export HADOOP_PREFIX ;;
    C) HADOOP_CONF_DIR="$OPTARG"; export HADOOP_CONF_DIR ;;
    J) JAVA_HOME="$OPTARG"; export JAVA_HOME ;;
    X) ARG_EXECARCH="$OPTARG" ;;
    K) ARG_TIMEOUT="$OPTARG" ;;
    M) ARG_MEM="$OPTARG" ;;
    T) TMPDIR="$(realpath "$OPTARG")"; export TMPDIR ;;
    k) ARG_KEEP="true" ;;
    D) ARG_DRYRUN="true" ;;
    v) echo "$version" && exit 0 ;;
    h) echo "$usage" && exit 0 ;;
    :) perror "option -$OPTARG requires an argument" && exit 1 ;;
    *) perror "option $opt is unknown" && exit 1 ;;
  esac
done
shift $((OPTIND-1))

### Check some key arguments

# make sure we have a simulation script
if [[ -z "$ARG_SLIMSCRIPT" ]]; then
  perror "No simulation script provided (did you forget -i ?)"
  exit 1
fi
# warn if only 1 simulation was requested, may be oversight
if [[ -z "$ARG_PARAMS" && "$ARG_NREPS" = 1 ]]; then
  pwarn "Only a single simulation requested; did you forget to use -n ?"
  pinfo "Continuing anyway ..."
fi
# check output path
if [[ -z "$ARG_OPATH" ]]; then
  perror "No output folder provided (use -o)"
  exit 1
else
  test -d "$ARG_OPATH" && \
    pwarn "Output folder $ARG_OPATH exists, contents may be overwritten!"
  mkdir -p "$ARG_OPATH"
  pinfo "Writing output to $ARG_OPATH ..."
fi

### TODO trap signals, errors, and clean up on exit
#trap 'perror "Command failed"; exit 4' ERR
# remember current directory so that we can reset it
cdir=$(pwd)
trap 'cd "$cdir"; if [[ "$ARG_KEEP" = "false" ]]; then rm -rf "$wdir"; else pinfo "Keeping data in $wdir"; fi' EXIT

### Main script starts here

pinfo "$0 $cmdline"
pinfo "pslim.sh v$version"
pinfo "Starting at $(date) ..."

# helper function to transform parameter script
function rmcolbyname
{
  exec 3>&0 0>&-
  torm="$1"
  read -r hdr <&3
  (( i=0 ))
  keep=""
  for h in $hdr; do
    (( i++ )) || true
    test "$h" = "$torm" && continue
    if [[ -z "$keep" ]]; then
      keep="$i"
    else
      keep="${keep},$i"
    fi
  done
  if [[ -n "$keep" ]]; then
    cut -f"$keep" < <(echo "$hdr"; cat <&3)
  fi
}

function getcolbyname
{
  exec 3>&0 0>&-
  toget="$1"
  read -r hdr <&3
  (( i=0 ))
  if for h in $hdr; do
    (( i++ )) || true
    test "$h" = "$toget" && break
  done; then
    cut -f"$i" <&3
  fi
}

function par2opt
{
  exec 3>&0 0>&-
  read -r hdr <&3
  while read -r line; do
    paste -d= <(printf -- '-define %s\n' $hdr) <(printf '\\"%s\\"\n' $line) | tr '\n' ' '
    echo
  done <&3
}

function mk_wdir
{
  local where wdir
  where="$1"
  wdir=$(mktemp -d -t pslim.XXXXX)
  # when using the cluster, we also need folders in the HDFS
  if [[ "$where" = "remote" ]]; then
    local wpath tpath tn
    wpath="$PSLIM_HDFS_WPATH"
    tpath="$PSLIM_HDFS_TPATH"
    tn=$(basename "$wdir")
    # find an unused temp name in the HDFS
    while hdfs dfs -test -e "$wpath/$tn" || hdfs dfs -test -e "$tpath/$tn"; do
      rmdir "$wdir"
      wdir=$(mktemp -d -t pslim.XXXXX)
      tn=$(basename "$wdir")
    done
    hdfs dfs -mkdir -p "$tpath/$tn" "$wpath/$tn/in"
    hdfs dfs -chmod 770 "$tpath/$tn"
  fi
  # populate
  # link shared input files, if any
  mkdir -p "$wdir/files"
  # make sure something is in there so that we can always make an archive
  touch "$wdir/files/foo"
  if [[ -n "$ARG_FILES" ]]; then
    for f in $ARG_FILES; do
      ln -sf "$(realpath "$f")" "$wdir/files/"
    done
  fi
  # generate seeds
  if [[ -n "$ARG_PARAMS" ]]; then
    # reset ARG_NREPS
    ARG_NREPS=$(($(wc -l "$ARG_PARAMS" | cut -f1 -d\ )-1))
    pinfo "Reset ARG_NREPS = $ARG_NREPS (the number of lines in the parameter file)."
    # do we have a seed?
    local hdr
    hdr=$(head -1 "$ARG_PARAMS")
    if for h in $hdr; do
      test "$h" = "seed" && break
    done; then
      # yes, extract seed column
      getcolbyname "seed" < "$ARG_PARAMS" > "$wdir/seeds.txt"
    fi
    # do we have files?
    if for h in $hdr; do
      test "$h" = "files" && break
    done; then
      # yes, extract files column
      getcolbyname "files" < "$ARG_PARAMS" > "$wdir/files.txt"
    fi
    # remove seed and files columns & transform into command line
    rmcolbyname "seed" < "$ARG_PARAMS" | rmcolbyname "files" |\
      par2opt > "$wdir/params.txt"
  fi
  # prepare a seed file from ARG_SEED
  test -f "$wdir/seeds.txt" || for x in $(seq 0 $((ARG_NREPS-1))); do
        printf "%i\n" $((x+ARG_SEED))
      done > "$wdir/seeds.txt"
  # make sure all files are here, if empty
  touch "$wdir/"{"seeds","files","params"}".txt"
  # return name
  echo "$wdir"
} 2>/dev/null

# run simulations locally with parallel
function run_sims_locally
{
  # check for slim
  if [[ -z "$PSLIM_SLIM_PATH" ]]; then
    if ! SLIM=$(which "slim"); then
      perror "Cannot find slim, exiting."
      exit 2
    fi
  else
    SLIM="$PSLIM_SLIM_PATH"
  fi
  if ! [[ -x "$SLIM" ]]; then
      perror "Cannot find slim executable $SLIM, exiting."
      exit 2
  else
    SLIM_VERSION=$(slim -version | head -1)
    pinfo "$SLIM_VERSION"
  fi
  # check for GNU parallel
  PARALLEL=$(which parallel)
  if ! [[ -x "$PARALLEL" ]]; then
    perror "parallel not found"
    exit 2
  else
    PARALLEL_VERSION=$(parallel --version | head -1)
    pinfo "$PARALLEL_VERSION"
  fi
  # make working folder and change into it
  wdir=$(mk_wdir)
  pinfo "Working in $wdir ..."
  cd "$wdir" || exit 3
  # organize input files for GNU parallel
  # and build command line
  # always have seed -> {1}
  pfls=":::: seeds.txt"
  # make script run by parallel
  # make a task-specific folder,
  # change into it and link the input file folder
  pscript="sdir=slim-{#}
   mkdir -p \\\$sdir
   cd \\\$sdir
   ln -s ../files 0files"
  # maybe files? -> {2}
  (( have_fls=0 ))
  if test -s "files.txt"; then
    pscript="$pscript
     mkdir 1files
     cd 1files
     for f in {=2 s/,/ /g=}; do
       if [[ \\\$f =~ ^/ ]]; then
         ln -s \\\$f
       else
         ln -s $cdir/\\\$f
       fi
     done
     cd .."
     pfls="$pfls :::: files.txt"
     (( have_fls=1 )) || true
  fi
  pscript="$pscript
   eval slim -time -mem -seed {1}"
  # maybe params? -> {2} or {3} depending on whether we have files
  if test -s "params.txt"; then
    pscript="$pscript {$((2+have_fls))}"
    pfls="$pfls :::: params.txt"
  fi
  pscript="$pscript $ARG_SLIMSCRIPT >slim.out 2>slim.err
   rm -f 0files
   rm -rf 1files
   cd ..
   mv -f \\\$sdir \"$ARG_OPATH/\""
  cmd="parallel --nice $ARG_NICENESS -j$ARG_THREADS --link \"$pscript\" $pfls"
  echo "$cmd" >&2
  if ! [[ $ARG_DRYRUN = "true" ]]; then
    eval "$cmd"
  fi
  cd "$cdir" || exit 4
}

# TODO debug below
function run_sims_on_cluster
{
   # execution on Hadoop
  # check for ARG_EXECARCH
  if [[ -z "$ARG_EXECARCH" ]]; then
    perror "Remote execution requested, but no executable archive provided"
    perror "(did you forget -X ?)"
    exit 2
  elif [[ "$ARG_EXECARCH" =~ ^(hdfs|file): ]]; then
    :
  else
    # assume it's a local path and prepend file://
    ARG_EXECARCH="file://$(realpath "$ARG_EXECARCH")"
  fi
  pinfo "Using slim binary provided in $ARG_EXECARCH ..."
  # prepare woring folder locally and on HDFS
  wdir=$(mk_wdir "remote")
  pinfo "Working in $wdir ..."
  cd "$wdir" || exit 3
  # generate mapper script
  # TODO where is the SLiM script called?
  cat <<'TOK' | sed -E "s@__PSLIM_HDFS_TPATH__@$PSLIM_HDFS_TPATH@;s@__wdir__@$(basename "$wdir")@" > "map.sh"
#!/bin/bash
set -o errexit
set -o pipefail
HADOOP_PREFIX="/opt/hadoop-current"
export PATH="$PATH:$HADOOP_PREFIX/bin"
tpath="__PSLIM_HDFS_TPATH__/__wdir__"
# turn stderr messages into Hadoop status reports
exec 2> >(while read -r MSG; do printf 'reporter:status:%s\n' "$MSG"; done >&2)
# redirect & close stdin so that commands do
# not accidentally read it before we are ready
exec 3>&0 0>&-
# make sure we don't leave processes around
trap 'pkill -P $$ || true' EXIT
hdfs dfs -mkdir -p "$tpath" >&2
(( i=0 )) || true
while IFS=$'\t' read -r SEED PARAMS FILES; do
  rm -rf "out" && mkdir -p "out" && cd "out"
  ln -s "../files" "0files"
  if [[ -n "$FILES" ]]; then
    echo "Downloading files ..." >&2
    mkdir -p "1files"
    for f in  $(echo "$FILES" | tr ',' ' '); do
      echo "Getting $f ..." >&2
      hdfs dfs -get "$f" "1files/" 2> "slim.err"
    done
  fi
  cmd="../bin/slim -time -mem -seed $SEED"
  if [[ -n "$PARAMS" ]]; then
    cmd="$cmd $PARAMS"
  fi
  cmd="$cmd ../runsim.slim"
  echo "$cmd" >&2
  eval "$cmd >slim.out 2>>slim.err"
  rm -f "0files"
  cd ..
  echo -ne "$SEED\t$PARAMS\t$FILES\t"
  hdfs dfs -put -f "out" "$tpath/slim-$mapreduce_task_partition-$i" && echo "OK" || echo "FAIL"
  (( i++ )) || true
done <&3
TOK
  chmod +x "map.sh"
  if ! [[ "$ARG_DRYRUN" = "true" ]]; then
    # find empty queue
    pinfo "Finding empty queue ..."
    while true; do
      queue=$(mapred queue -list 2>/dev/null | \
            grep -B2 "CurrentCapacity: 0.0" | \
            grep "^Queue Name" | cut -f4 -d\ | tail -1)
      if [[ -n "$queue" ]]; then
        break
      fi
      pinfo "All queues in use at $(date); retrying in 5 min ..."
      sleep 300
    done
    pinfo "Using queue $queue ..."
    # generate tasks and start Hadoop job
    hbase="$HADOOP_PREFIX/share/hadoop/tools/lib"
    hadoop_streaming_jar=$(find "$hbase" -name "hadoop-streaming-*.jar" | tail -1)
    hadoop_4mc_jar=$(find "$hbase" -name "hadoop-4mc-*.jar" | tail -1)
    # need an input.txt file that has seed, parameters, files in three columns
    hpath="$PSLIM_HDFS_WPATH/$(basename "$wdir")"
    paste "seeds.txt" "params.txt" "files.txt" | hdfs dfs -put - "$hpath/in/input.txt"
    # common files to upload
    cd "files" && tar -czhf "../files.tgz" -- * && cd ..
    FILE_ARCHIVE="$(realpath "files.tgz")"
    hadoop jar "$hadoop_streaming_jar"\
        -libjars "$hadoop_4mc_jar"\
        -files "file://$wdir/map.sh,file://${ARG_SLIMSCRIPT}#runsim.slim"\
        -archives "${ARG_EXECARCH}#bin,file://$FILE_ARCHIVE#files"\
        -D mapreduce.job.queuename="$queue"\
        -D mapreduce.job.name="$(basename "$wdir")"\
        -D mapreduce.job.maps="$ARG_NREPS"\
        -D mapreduce.map.memory.mb="$ARG_MEM"\
        -D mapreduce.task.timeout="$ARG_TIMEOUT"\
        -D mapreduce.map.maxattempts=10\
        -input "$hpath/in/input.txt" -output "$hpath/out" \
        -mapper map.sh -reducer /bin/cat
    # download outputs into output folder
    hdfs dfs -get -f "$PSLIM_HDFS_TPATH/$(basename "$wdir")/*" "$ARG_OPATH/"
  fi
}

### main script

if [[ "$ARG_REMOTE" = "false" ]]; then
  run_sims_locally
else
  run_sims_on_cluster
fi

pinfo "All done at $(date)."
